version: '3'
services:
  app:
    build: ./php
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/mysql.conf:/etc/mysql/conf.d/my.cnf